language: java


jdk:
  - openjdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lib32stdc++6 lib32z1

install:
    - make sdk
    - make ndk
    - make prop
    - make 

script:
    - ls